"""
utils/notebook_exporter.py — Converts a CoScientist research session into a reproducible Jupyter Notebook (.ipynb).
"""

import json
import logging
from typing import Any

logger = logging.getLogger(__name__)


def generate_reproducible_notebook(co_scientist: Any, output_path: str = "experiment_protocol.ipynb") -> str:
    """
    Generate an executable Jupyter Notebook (.ipynb) containing:
    1. Research Goal overview
    2. Top Hypothesis mechanism & predictions
    3. Executable Python experimental validation code
    4. Data analysis & visualization script
    """
    goal = co_scientist.context_memory.research_goal
    hypotheses = list(co_scientist.context_memory.hypotheses.values())
    top_hyp = max(hypotheses, key=lambda h: h.elo_rating) if hypotheses else None

    title = goal.title if goal else "AI Co-Scientist Research Protocol"
    desc = goal.description if goal else "Reproducible experiment notebook."

    cells = []

    # Title Cell
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            f"# 🔬 Reproducible Research Protocol: {title}\n",
            f"**Generated by NewAI Scientist v3.1**\n\n",
            f"### 📋 Research Goal\n",
            f"{desc}\n"
        ]
    })

    # Hypothesis Section
    if top_hyp:
        cells.append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                f"## 💡 Target Hypothesis: {top_hyp.title}\n",
                f"- **Elo Rating:** {top_hyp.elo_rating:.0f}\n",
                f"- **Novelty Level:** {top_hyp.novelty_level}\n\n",
                f"### ⚙️ Proposed Mechanism\n",
                f"{top_hyp.mechanism}\n\n",
                f"### 🧪 Testable Predictions\n",
                "\n".join(f"- {p}" for p in (top_hyp.testable_predictions or ["No specific prediction listed."]))
            ]
        })

        # Code Cell for Setup
        cells.append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Environment Setup & Requirements\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "sns.set_theme(style='darkgrid')\n",
                "print('Environment ready for hypothesis verification.')\n"
            ]
        })

        # Code Cell for Experimental Code
        exp_code = getattr(top_hyp, "experimental_results", "")
        if exp_code:
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 🧪 Empirical Experimentation Code\n",
                    "Below is the executable Python code generated to test predictions for this hypothesis:"
                ]
            })

            clean_code = exp_code
            if "```python" in clean_code:
                clean_code = clean_code.split("```python")[1].split("```")[0].strip()
            elif "```" in clean_code:
                clean_code = clean_code.split("```")[1].split("```")[0].strip()

            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": clean_code.splitlines(keepends=True)
            })

    # Statistical Analysis Cell
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 📊 Statistical Analysis & Data Visualization\n",
            "Execute the code below to plot distribution metrics and confidence bounds for experimental outcomes:"
        ]
    })

    cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Synthetic data generation based on experimental protocol\n",
            "np.random.seed(42)\n",
            "control = np.random.normal(loc=10.0, scale=2.0, size=100)\n",
            "treatment = np.random.normal(loc=14.5, scale=2.2, size=100)\n\n",
            "df = pd.DataFrame({'Control': control, 'Treatment': treatment})\n",
            "plt.figure(figsize=(8, 5))\n",
            "sns.boxplot(data=df, palette='Set2')\n",
            "plt.title('Experimental Outcome Comparison (Control vs Treatment)')\n",
            "plt.ylabel('Response Metric')\n",
            "plt.show()\n"
        ]
    })

    notebook = {
        "cells": cells,
        "metadata": {
            "language_info": {
                "name": "python",
                "version": "3.10"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)

    logger.info("Generated reproducible Jupyter Notebook at %s", output_path)
    return output_path
